// Code generated by protoc-gen-go.
// source: github.com/codelingo/rpc/flow/flow.proto
// DO NOT EDIT!

/*
Package flow is a generated protocol buffer package.

It is generated from these files:
	github.com/codelingo/rpc/flow/flow.proto

It has these top-level messages:
	ReviewRequest
	Issue
	IssueRange
	Position
	SearchRequest
	SearchReply
	PropertyValue
*/
package flow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the files or directories to review.
type ReviewRequest struct {
	Host     string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	// Types that are valid to be assigned to OwnerOrDepot:
	//	*ReviewRequest_Owner
	//	*ReviewRequest_Depot
	OwnerOrDepot  isReviewRequest_OwnerOrDepot `protobuf_oneof:"ownerOrDepot"`
	Repo          string                       `protobuf:"bytes,4,opt,name=repo" json:"repo,omitempty"`
	Sha           string                       `protobuf:"bytes,5,opt,name=sha" json:"sha,omitempty"`
	Patches       []string                     `protobuf:"bytes,6,rep,name=Patches" json:"Patches,omitempty"`
	IsPullRequest bool                         `protobuf:"varint,7,opt,name=isPullRequest" json:"isPullRequest,omitempty"`
	PullRequestID int64                        `protobuf:"varint,8,opt,name=pullRequestID" json:"pullRequestID,omitempty"`
	Vcs           string                       `protobuf:"bytes,9,opt,name=vcs" json:"vcs,omitempty"`
	Dotlingo      string                       `protobuf:"bytes,10,opt,name=dotlingo" json:"dotlingo,omitempty"`
	Dir           string                       `protobuf:"bytes,11,opt,name=dir" json:"dir,omitempty"`
}

func (m *ReviewRequest) Reset()                    { *m = ReviewRequest{} }
func (m *ReviewRequest) String() string            { return proto.CompactTextString(m) }
func (*ReviewRequest) ProtoMessage()               {}
func (*ReviewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isReviewRequest_OwnerOrDepot interface {
	isReviewRequest_OwnerOrDepot()
}

type ReviewRequest_Owner struct {
	Owner string `protobuf:"bytes,12,opt,name=owner,oneof"`
}
type ReviewRequest_Depot struct {
	Depot string `protobuf:"bytes,13,opt,name=depot,oneof"`
}

func (*ReviewRequest_Owner) isReviewRequest_OwnerOrDepot() {}
func (*ReviewRequest_Depot) isReviewRequest_OwnerOrDepot() {}

func (m *ReviewRequest) GetOwnerOrDepot() isReviewRequest_OwnerOrDepot {
	if m != nil {
		return m.OwnerOrDepot
	}
	return nil
}

func (m *ReviewRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ReviewRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ReviewRequest) GetOwner() string {
	if x, ok := m.GetOwnerOrDepot().(*ReviewRequest_Owner); ok {
		return x.Owner
	}
	return ""
}

func (m *ReviewRequest) GetDepot() string {
	if x, ok := m.GetOwnerOrDepot().(*ReviewRequest_Depot); ok {
		return x.Depot
	}
	return ""
}

func (m *ReviewRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *ReviewRequest) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *ReviewRequest) GetPatches() []string {
	if m != nil {
		return m.Patches
	}
	return nil
}

func (m *ReviewRequest) GetIsPullRequest() bool {
	if m != nil {
		return m.IsPullRequest
	}
	return false
}

func (m *ReviewRequest) GetPullRequestID() int64 {
	if m != nil {
		return m.PullRequestID
	}
	return 0
}

func (m *ReviewRequest) GetVcs() string {
	if m != nil {
		return m.Vcs
	}
	return ""
}

func (m *ReviewRequest) GetDotlingo() string {
	if m != nil {
		return m.Dotlingo
	}
	return ""
}

func (m *ReviewRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReviewRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReviewRequest_OneofMarshaler, _ReviewRequest_OneofUnmarshaler, _ReviewRequest_OneofSizer, []interface{}{
		(*ReviewRequest_Owner)(nil),
		(*ReviewRequest_Depot)(nil),
	}
}

func _ReviewRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReviewRequest)
	// ownerOrDepot
	switch x := m.OwnerOrDepot.(type) {
	case *ReviewRequest_Owner:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Owner)
	case *ReviewRequest_Depot:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Depot)
	case nil:
	default:
		return fmt.Errorf("ReviewRequest.OwnerOrDepot has unexpected type %T", x)
	}
	return nil
}

func _ReviewRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReviewRequest)
	switch tag {
	case 12: // ownerOrDepot.owner
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OwnerOrDepot = &ReviewRequest_Owner{x}
		return true, err
	case 13: // ownerOrDepot.depot
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OwnerOrDepot = &ReviewRequest_Depot{x}
		return true, err
	default:
		return false, nil
	}
}

func _ReviewRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReviewRequest)
	// ownerOrDepot
	switch x := m.OwnerOrDepot.(type) {
	case *ReviewRequest_Owner:
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Owner)))
		n += len(x.Owner)
	case *ReviewRequest_Depot:
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Depot)))
		n += len(x.Depot)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Issue returned from a review.
type Issue struct {
	// The name of the issue.
	Name          string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Position      *IssueRange       `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Comment       string            `protobuf:"bytes,3,opt,name=comment" json:"comment,omitempty"`
	CtxBefore     string            `protobuf:"bytes,4,opt,name=ctxBefore" json:"ctxBefore,omitempty"`
	LineText      string            `protobuf:"bytes,5,opt,name=lineText" json:"lineText,omitempty"`
	CtxAfter      string            `protobuf:"bytes,6,opt,name=ctxAfter" json:"ctxAfter,omitempty"`
	Metrics       map[string]string `protobuf:"bytes,7,rep,name=metrics" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string          `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
	Link          string            `protobuf:"bytes,9,opt,name=link" json:"link,omitempty"`
	NewCode       bool              `protobuf:"varint,10,opt,name=newCode" json:"newCode,omitempty"`
	Patch         string            `protobuf:"bytes,11,opt,name=patch" json:"patch,omitempty"`
	Err           string            `protobuf:"bytes,12,opt,name=err" json:"err,omitempty"`
	Discard       bool              `protobuf:"varint,13,opt,name=discard" json:"discard,omitempty"`
	DiscardReason string            `protobuf:"bytes,14,opt,name=discardReason" json:"discardReason,omitempty"`
	// isHeartbeat is used to periodically send pings from the server to keep long running connections alive.
	// clients can safely ignore this field as no other data will be sent with it.
	IsHeartbeat bool `protobuf:"varint,15,opt,name=isHeartbeat" json:"isHeartbeat,omitempty"`
}

func (m *Issue) Reset()                    { *m = Issue{} }
func (m *Issue) String() string            { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()               {}
func (*Issue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Issue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Issue) GetPosition() *IssueRange {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Issue) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Issue) GetCtxBefore() string {
	if m != nil {
		return m.CtxBefore
	}
	return ""
}

func (m *Issue) GetLineText() string {
	if m != nil {
		return m.LineText
	}
	return ""
}

func (m *Issue) GetCtxAfter() string {
	if m != nil {
		return m.CtxAfter
	}
	return ""
}

func (m *Issue) GetMetrics() map[string]string {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Issue) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Issue) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Issue) GetNewCode() bool {
	if m != nil {
		return m.NewCode
	}
	return false
}

func (m *Issue) GetPatch() string {
	if m != nil {
		return m.Patch
	}
	return ""
}

func (m *Issue) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *Issue) GetDiscard() bool {
	if m != nil {
		return m.Discard
	}
	return false
}

func (m *Issue) GetDiscardReason() string {
	if m != nil {
		return m.DiscardReason
	}
	return ""
}

func (m *Issue) GetIsHeartbeat() bool {
	if m != nil {
		return m.IsHeartbeat
	}
	return false
}

type IssueRange struct {
	Start *Position `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End   *Position `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
}

func (m *IssueRange) Reset()                    { *m = IssueRange{} }
func (m *IssueRange) String() string            { return proto.CompactTextString(m) }
func (*IssueRange) ProtoMessage()               {}
func (*IssueRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IssueRange) GetStart() *Position {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *IssueRange) GetEnd() *Position {
	if m != nil {
		return m.End
	}
	return nil
}

type Position struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Offset   int64  `protobuf:"varint,2,opt,name=Offset" json:"Offset,omitempty"`
	Line     int64  `protobuf:"varint,3,opt,name=Line" json:"Line,omitempty"`
	Column   int64  `protobuf:"varint,4,opt,name=Column" json:"Column,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Position) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Position) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Position) GetLine() int64 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Position) GetColumn() int64 {
	if m != nil {
		return m.Column
	}
	return 0
}

type SearchRequest struct {
	Dotlingo string `protobuf:"bytes,1,opt,name=dotlingo" json:"dotlingo,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchRequest) GetDotlingo() string {
	if m != nil {
		return m.Dotlingo
	}
	return ""
}

type SearchReply struct {
	Properties map[string]*PropertyValue `protobuf:"bytes,1,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error      string                    `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Depth      int64                     `protobuf:"varint,3,opt,name=depth" json:"depth,omitempty"`
	FactName   string                    `protobuf:"bytes,4,opt,name=factName" json:"factName,omitempty"`
	Decorators []string                  `protobuf:"bytes,5,rep,name=decorators" json:"decorators,omitempty"`
	Children   []*SearchReply            `protobuf:"bytes,6,rep,name=children" json:"children,omitempty"`
}

func (m *SearchReply) Reset()                    { *m = SearchReply{} }
func (m *SearchReply) String() string            { return proto.CompactTextString(m) }
func (*SearchReply) ProtoMessage()               {}
func (*SearchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchReply) GetProperties() map[string]*PropertyValue {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *SearchReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SearchReply) GetDepth() int64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *SearchReply) GetFactName() string {
	if m != nil {
		return m.FactName
	}
	return ""
}

func (m *SearchReply) GetDecorators() []string {
	if m != nil {
		return m.Decorators
	}
	return nil
}

func (m *SearchReply) GetChildren() []*SearchReply {
	if m != nil {
		return m.Children
	}
	return nil
}

type PropertyValue struct {
	// Types that are valid to be assigned to Prop:
	//	*PropertyValue_StringProp
	//	*PropertyValue_BoolProp
	//	*PropertyValue_Int64Prop
	//	*PropertyValue_FloatProp
	Prop       isPropertyValue_Prop `protobuf_oneof:"prop"`
	Decorators []string             `protobuf:"bytes,5,rep,name=decorators" json:"decorators,omitempty"`
}

func (m *PropertyValue) Reset()                    { *m = PropertyValue{} }
func (m *PropertyValue) String() string            { return proto.CompactTextString(m) }
func (*PropertyValue) ProtoMessage()               {}
func (*PropertyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isPropertyValue_Prop interface {
	isPropertyValue_Prop()
}

type PropertyValue_StringProp struct {
	StringProp string `protobuf:"bytes,1,opt,name=stringProp,oneof"`
}
type PropertyValue_BoolProp struct {
	BoolProp bool `protobuf:"varint,2,opt,name=boolProp,oneof"`
}
type PropertyValue_Int64Prop struct {
	Int64Prop int64 `protobuf:"varint,3,opt,name=int64Prop,oneof"`
}
type PropertyValue_FloatProp struct {
	FloatProp float32 `protobuf:"fixed32,4,opt,name=floatProp,oneof"`
}

func (*PropertyValue_StringProp) isPropertyValue_Prop() {}
func (*PropertyValue_BoolProp) isPropertyValue_Prop()   {}
func (*PropertyValue_Int64Prop) isPropertyValue_Prop()  {}
func (*PropertyValue_FloatProp) isPropertyValue_Prop()  {}

func (m *PropertyValue) GetProp() isPropertyValue_Prop {
	if m != nil {
		return m.Prop
	}
	return nil
}

func (m *PropertyValue) GetStringProp() string {
	if x, ok := m.GetProp().(*PropertyValue_StringProp); ok {
		return x.StringProp
	}
	return ""
}

func (m *PropertyValue) GetBoolProp() bool {
	if x, ok := m.GetProp().(*PropertyValue_BoolProp); ok {
		return x.BoolProp
	}
	return false
}

func (m *PropertyValue) GetInt64Prop() int64 {
	if x, ok := m.GetProp().(*PropertyValue_Int64Prop); ok {
		return x.Int64Prop
	}
	return 0
}

func (m *PropertyValue) GetFloatProp() float32 {
	if x, ok := m.GetProp().(*PropertyValue_FloatProp); ok {
		return x.FloatProp
	}
	return 0
}

func (m *PropertyValue) GetDecorators() []string {
	if m != nil {
		return m.Decorators
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PropertyValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PropertyValue_OneofMarshaler, _PropertyValue_OneofUnmarshaler, _PropertyValue_OneofSizer, []interface{}{
		(*PropertyValue_StringProp)(nil),
		(*PropertyValue_BoolProp)(nil),
		(*PropertyValue_Int64Prop)(nil),
		(*PropertyValue_FloatProp)(nil),
	}
}

func _PropertyValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PropertyValue)
	// prop
	switch x := m.Prop.(type) {
	case *PropertyValue_StringProp:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringProp)
	case *PropertyValue_BoolProp:
		t := uint64(0)
		if x.BoolProp {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *PropertyValue_Int64Prop:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int64Prop))
	case *PropertyValue_FloatProp:
		b.EncodeVarint(4<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatProp)))
	case nil:
	default:
		return fmt.Errorf("PropertyValue.Prop has unexpected type %T", x)
	}
	return nil
}

func _PropertyValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PropertyValue)
	switch tag {
	case 1: // prop.stringProp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Prop = &PropertyValue_StringProp{x}
		return true, err
	case 2: // prop.boolProp
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Prop = &PropertyValue_BoolProp{x != 0}
		return true, err
	case 3: // prop.int64Prop
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Prop = &PropertyValue_Int64Prop{int64(x)}
		return true, err
	case 4: // prop.floatProp
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Prop = &PropertyValue_FloatProp{math.Float32frombits(uint32(x))}
		return true, err
	default:
		return false, nil
	}
}

func _PropertyValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PropertyValue)
	// prop
	switch x := m.Prop.(type) {
	case *PropertyValue_StringProp:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringProp)))
		n += len(x.StringProp)
	case *PropertyValue_BoolProp:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += 1
	case *PropertyValue_Int64Prop:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int64Prop))
	case *PropertyValue_FloatProp:
		n += proto.SizeVarint(4<<3 | proto.WireFixed32)
		n += 4
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ReviewRequest)(nil), "flow.ReviewRequest")
	proto.RegisterType((*Issue)(nil), "flow.Issue")
	proto.RegisterType((*IssueRange)(nil), "flow.IssueRange")
	proto.RegisterType((*Position)(nil), "flow.Position")
	proto.RegisterType((*SearchRequest)(nil), "flow.SearchRequest")
	proto.RegisterType((*SearchReply)(nil), "flow.SearchReply")
	proto.RegisterType((*PropertyValue)(nil), "flow.PropertyValue")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Flow service

type FlowClient interface {
	// Reviews files
	Review(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (Flow_ReviewClient, error)
	Codemod(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (Flow_CodemodClient, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Flow_SearchClient, error)
}

type flowClient struct {
	cc *grpc.ClientConn
}

func NewFlowClient(cc *grpc.ClientConn) FlowClient {
	return &flowClient{cc}
}

func (c *flowClient) Review(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (Flow_ReviewClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Flow_serviceDesc.Streams[0], c.cc, "/flow.Flow/Review", opts...)
	if err != nil {
		return nil, err
	}
	x := &flowReviewClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Flow_ReviewClient interface {
	Recv() (*Issue, error)
	grpc.ClientStream
}

type flowReviewClient struct {
	grpc.ClientStream
}

func (x *flowReviewClient) Recv() (*Issue, error) {
	m := new(Issue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *flowClient) Codemod(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (Flow_CodemodClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Flow_serviceDesc.Streams[1], c.cc, "/flow.Flow/Codemod", opts...)
	if err != nil {
		return nil, err
	}
	x := &flowCodemodClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Flow_CodemodClient interface {
	Recv() (*Issue, error)
	grpc.ClientStream
}

type flowCodemodClient struct {
	grpc.ClientStream
}

func (x *flowCodemodClient) Recv() (*Issue, error) {
	m := new(Issue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *flowClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Flow_SearchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Flow_serviceDesc.Streams[2], c.cc, "/flow.Flow/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &flowSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Flow_SearchClient interface {
	Recv() (*SearchReply, error)
	grpc.ClientStream
}

type flowSearchClient struct {
	grpc.ClientStream
}

func (x *flowSearchClient) Recv() (*SearchReply, error) {
	m := new(SearchReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Flow service

type FlowServer interface {
	// Reviews files
	Review(*ReviewRequest, Flow_ReviewServer) error
	Codemod(*ReviewRequest, Flow_CodemodServer) error
	Search(*SearchRequest, Flow_SearchServer) error
}

func RegisterFlowServer(s *grpc.Server, srv FlowServer) {
	s.RegisterService(&_Flow_serviceDesc, srv)
}

func _Flow_Review_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReviewRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowServer).Review(m, &flowReviewServer{stream})
}

type Flow_ReviewServer interface {
	Send(*Issue) error
	grpc.ServerStream
}

type flowReviewServer struct {
	grpc.ServerStream
}

func (x *flowReviewServer) Send(m *Issue) error {
	return x.ServerStream.SendMsg(m)
}

func _Flow_Codemod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReviewRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowServer).Codemod(m, &flowCodemodServer{stream})
}

type Flow_CodemodServer interface {
	Send(*Issue) error
	grpc.ServerStream
}

type flowCodemodServer struct {
	grpc.ServerStream
}

func (x *flowCodemodServer) Send(m *Issue) error {
	return x.ServerStream.SendMsg(m)
}

func _Flow_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowServer).Search(m, &flowSearchServer{stream})
}

type Flow_SearchServer interface {
	Send(*SearchReply) error
	grpc.ServerStream
}

type flowSearchServer struct {
	grpc.ServerStream
}

func (x *flowSearchServer) Send(m *SearchReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Flow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flow.Flow",
	HandlerType: (*FlowServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Review",
			Handler:       _Flow_Review_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Codemod",
			Handler:       _Flow_Codemod_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Search",
			Handler:       _Flow_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/codelingo/rpc/flow/flow.proto",
}

func init() { proto.RegisterFile("github.com/codelingo/rpc/flow/flow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 887 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0x5f, 0x8f, 0x1b, 0x35,
	0x10, 0xcf, 0x66, 0xf3, 0x67, 0x33, 0xb9, 0x5c, 0x8b, 0xa9, 0x2a, 0x2b, 0xaa, 0xaa, 0x10, 0xf5,
	0x21, 0x08, 0xd8, 0x43, 0xa1, 0x42, 0xa8, 0x6f, 0xcd, 0x15, 0x94, 0x4a, 0x07, 0x8d, 0x4c, 0x05,
	0xcf, 0x7b, 0xbb, 0x93, 0xc4, 0x74, 0xb3, 0x5e, 0x6c, 0xe7, 0x72, 0xf7, 0x61, 0x78, 0xe1, 0x4b,
	0xf0, 0xc0, 0x47, 0xe0, 0xf3, 0xf0, 0x8e, 0xc6, 0xde, 0xcd, 0x6d, 0x5a, 0x24, 0x78, 0x49, 0xe6,
	0xf7, 0x9b, 0xf1, 0xd8, 0xf3, 0x9b, 0xf1, 0x1a, 0x66, 0x1b, 0x69, 0xb7, 0xfb, 0xeb, 0x38, 0x55,
	0xbb, 0x8b, 0x54, 0x65, 0x98, 0xcb, 0x62, 0xa3, 0x2e, 0x74, 0x99, 0x5e, 0xac, 0x73, 0x75, 0x70,
	0x3f, 0x71, 0xa9, 0x95, 0x55, 0xac, 0x43, 0xf6, 0xf4, 0xaf, 0x36, 0x8c, 0x04, 0xde, 0x48, 0x3c,
	0x08, 0xfc, 0x75, 0x8f, 0xc6, 0x32, 0x06, 0x9d, 0xad, 0x32, 0x96, 0x07, 0x93, 0x60, 0x36, 0x10,
	0xce, 0x66, 0x63, 0x88, 0xe8, 0xbf, 0x48, 0x76, 0xc8, 0xdb, 0x8e, 0x3f, 0x62, 0xf6, 0x18, 0xba,
	0xea, 0x50, 0xa0, 0xe6, 0x67, 0xe4, 0x58, 0xb6, 0x84, 0x87, 0xc4, 0x67, 0x58, 0x2a, 0xcb, 0x47,
	0x35, 0xef, 0x20, 0xe5, 0xd7, 0x58, 0x2a, 0xde, 0xf1, 0xf9, 0xc9, 0x66, 0x0f, 0x21, 0x34, 0xdb,
	0x84, 0x77, 0x1d, 0x45, 0x26, 0xe3, 0xd0, 0x5f, 0x25, 0x36, 0xdd, 0xa2, 0xe1, 0xbd, 0x49, 0x38,
	0x1b, 0x88, 0x1a, 0xb2, 0x67, 0x30, 0x92, 0x66, 0xb5, 0xcf, 0xf3, 0xea, 0xc0, 0xbc, 0x3f, 0x09,
	0x66, 0x91, 0x38, 0x25, 0x29, 0xaa, 0xbc, 0x87, 0xaf, 0x5f, 0xf1, 0x68, 0x12, 0xcc, 0x42, 0x71,
	0x4a, 0xd2, 0xbe, 0x37, 0xa9, 0xe1, 0x03, 0xbf, 0xef, 0x4d, 0x6a, 0xa8, 0xd2, 0x4c, 0x59, 0xa7,
	0x1a, 0x07, 0x5f, 0x69, 0x8d, 0x29, 0x3a, 0x93, 0x9a, 0x0f, 0x7d, 0x74, 0x26, 0xf5, 0xe2, 0x1c,
	0xce, 0x5c, 0xb1, 0x6f, 0xf4, 0x2b, 0xaa, 0x6d, 0xfa, 0x77, 0x08, 0xdd, 0xd7, 0xc6, 0xec, 0x91,
	0xaa, 0x74, 0x6a, 0x55, 0x2a, 0x3a, 0xa5, 0x3e, 0x87, 0xa8, 0x54, 0x46, 0x5a, 0xa9, 0x0a, 0xa7,
	0xe2, 0x70, 0xfe, 0x30, 0x76, 0x0d, 0x71, 0x4b, 0x44, 0x52, 0x6c, 0x50, 0x1c, 0x23, 0x48, 0x81,
	0x54, 0xed, 0x76, 0x58, 0x58, 0x1e, 0xba, 0x24, 0x35, 0x64, 0x4f, 0x60, 0x90, 0xda, 0xdb, 0x05,
	0xae, 0x95, 0xc6, 0x4a, 0xc6, 0x7b, 0x82, 0x2a, 0xc8, 0x65, 0x81, 0x6f, 0xf1, 0xd6, 0x56, 0x82,
	0x1e, 0x31, 0xf9, 0x52, 0x7b, 0xfb, 0x72, 0x6d, 0x51, 0xf3, 0x9e, 0xf7, 0xd5, 0x98, 0xcd, 0xa1,
	0xbf, 0x43, 0xab, 0x65, 0x6a, 0x78, 0x7f, 0x12, 0xce, 0x86, 0x73, 0xde, 0x38, 0x5c, 0xfc, 0xbd,
	0x77, 0x7d, 0x5b, 0x58, 0x7d, 0x27, 0xea, 0x40, 0xaa, 0xd2, 0x26, 0x1b, 0xc3, 0x23, 0xd7, 0x22,
	0x67, 0x13, 0x97, 0xcb, 0xe2, 0x5d, 0x25, 0xaa, 0xb3, 0xa9, 0x96, 0x02, 0x0f, 0x97, 0x2a, 0x43,
	0x27, 0x6a, 0x24, 0x6a, 0xc8, 0x1e, 0x41, 0xb7, 0xa4, 0xc6, 0x56, 0xaa, 0x7a, 0x40, 0x4a, 0xa3,
	0xae, 0x26, 0x4a, 0x90, 0x49, 0x19, 0x32, 0x69, 0xd2, 0x44, 0x67, 0x6e, 0x9e, 0x22, 0x51, 0x43,
	0xea, 0x74, 0x65, 0x0a, 0x4c, 0x8c, 0x2a, 0xf8, 0xb9, 0x5b, 0x75, 0x4a, 0xb2, 0x09, 0x0c, 0xa5,
	0x59, 0x62, 0xa2, 0xed, 0x35, 0x26, 0x96, 0x3f, 0x70, 0x39, 0x9a, 0xd4, 0xf8, 0x05, 0x9c, 0x35,
	0x8b, 0xa4, 0x33, 0xbc, 0xc3, 0xbb, 0xaa, 0x81, 0x64, 0xd2, 0x59, 0x6f, 0x92, 0x7c, 0x5f, 0x5f,
	0x01, 0x0f, 0x5e, 0xb4, 0xbf, 0x09, 0xa6, 0x6f, 0x01, 0xee, 0x7b, 0xc8, 0x9e, 0x41, 0xd7, 0xd8,
	0x44, 0xfb, 0x2b, 0x34, 0x9c, 0x9f, 0x7b, 0x1d, 0x57, 0x55, 0x63, 0x85, 0x77, 0xb2, 0x09, 0x84,
	0x58, 0x64, 0xd5, 0x20, 0xbc, 0x1f, 0x43, 0xae, 0xe9, 0x2f, 0x10, 0xd5, 0x04, 0x75, 0x6e, 0x2d,
	0x73, 0x6c, 0xcc, 0xd4, 0x11, 0xb3, 0xc7, 0xd0, 0x7b, 0xb3, 0x5e, 0x1b, 0xb4, 0x2e, 0x59, 0x28,
	0x2a, 0x44, 0x9d, 0xb8, 0x92, 0x05, 0xba, 0xf1, 0x09, 0x85, 0xb3, 0x29, 0xf6, 0x52, 0xe5, 0xfb,
	0x5d, 0xe1, 0x06, 0x27, 0x14, 0x15, 0x9a, 0x7e, 0x06, 0xa3, 0x1f, 0x31, 0xd1, 0xe9, 0xb6, 0xbe,
	0x40, 0xcd, 0x8b, 0x10, 0x9c, 0x5e, 0x84, 0xe9, 0x9f, 0x6d, 0x18, 0xd6, 0xd1, 0x65, 0x7e, 0xc7,
	0x5e, 0x02, 0x94, 0x5a, 0x95, 0xa8, 0xad, 0x44, 0xc3, 0x03, 0x37, 0x3d, 0x9f, 0xf8, 0x8a, 0x1a,
	0x61, 0xf1, 0xea, 0x18, 0xe3, 0xc7, 0xa8, 0xb1, 0x88, 0xb4, 0x45, 0xad, 0x95, 0xae, 0xb5, 0x75,
	0x80, 0xd8, 0x0c, 0x4b, 0xbb, 0xad, 0x4a, 0xf0, 0xc0, 0x69, 0x91, 0xa4, 0xf6, 0x07, 0xd2, 0xa2,
	0x53, 0x69, 0x51, 0x61, 0xf6, 0x14, 0x20, 0xc3, 0x54, 0xe9, 0xc4, 0x2a, 0x6d, 0x78, 0xd7, 0xcd,
	0x65, 0x83, 0x61, 0x5f, 0x40, 0x94, 0x6e, 0x65, 0x9e, 0x69, 0x2c, 0xdc, 0x87, 0x65, 0x38, 0xff,
	0xe8, 0x83, 0x83, 0x8a, 0x63, 0xc8, 0x58, 0xc0, 0x83, 0xf7, 0x4e, 0xfd, 0x2f, 0x73, 0xf1, 0x69,
	0x73, 0x2e, 0x86, 0xf3, 0x8f, 0xab, 0x5e, 0xfa, 0x75, 0x77, 0x3f, 0x91, 0xab, 0x39, 0x2c, 0x7f,
	0x04, 0x30, 0x3a, 0x71, 0xb2, 0x09, 0x80, 0xb1, 0x5a, 0x16, 0x1b, 0xa2, 0x7d, 0xe6, 0x65, 0x4b,
	0x34, 0x38, 0xf6, 0x04, 0xa2, 0x6b, 0xa5, 0x72, 0xe7, 0xa7, 0x5d, 0xa2, 0x65, 0x4b, 0x1c, 0x19,
	0xf6, 0x14, 0x06, 0xb2, 0xb0, 0x5f, 0x3f, 0x77, 0x6e, 0x27, 0xd5, 0xb2, 0x25, 0xee, 0x29, 0xf2,
	0xaf, 0x73, 0x95, 0x58, 0xe7, 0x27, 0xc5, 0xda, 0xe4, 0x3f, 0x52, 0xff, 0x25, 0xda, 0xa2, 0x07,
	0x1d, 0x6a, 0xd5, 0xfc, 0xb7, 0x00, 0x3a, 0xdf, 0xe5, 0xea, 0xc0, 0x62, 0xe8, 0xf9, 0x47, 0x83,
	0x55, 0xc5, 0x9e, 0x3c, 0x21, 0xe3, 0x61, 0xe3, 0xcb, 0x31, 0x6d, 0x7d, 0x19, 0xb0, 0x0b, 0xe8,
	0xd3, 0x6d, 0xdf, 0xa9, 0xec, 0x7f, 0x2e, 0x78, 0x0e, 0x3d, 0xdf, 0x90, 0x3a, 0xfe, 0x64, 0x38,
	0xc7, 0x1f, 0xf6, 0x8c, 0x56, 0x2d, 0x62, 0x78, 0x24, 0x55, 0x7c, 0x7c, 0xf6, 0xe2, 0x8d, 0x2e,
	0xd3, 0x38, 0xcd, 0x17, 0xe7, 0xb4, 0xf9, 0x15, 0x51, 0x2b, 0x7a, 0xfa, 0x56, 0xc1, 0xef, 0xed,
	0xf0, 0xf2, 0xea, 0xe7, 0xeb, 0x9e, 0x7b, 0x09, 0xbf, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc2,
	0x92, 0x3b, 0x59, 0x35, 0x07, 0x00, 0x00,
}
